version: 0.2
phases:

  build:
    commands:
      - docker --version
      - cd docker_files
      - cd web 
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 921302943194.dkr.ecr.eu-west-3.amazonaws.com
      - docker build -t container_node .
      - docker tag container_node:latest 921302943194.dkr.ecr.eu-west-3.amazonaws.com/container_node:latest
      - docker push 921302943194.dkr.ecr.eu-west-3.amazonaws.com/container_node:latest
