version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate

  build:
    commands:
      - terraform plan -out plan.plan
      - bash send_notification.sh
      
artifacts:
  files:
    - 'plan.plan'